# config/generation_config.yaml

# Generation settings
generation:
  num_samples: 1000
  max_cycles: 2000
  breakdown_threshold: 0.95  # Probability threshold
  
# Parameter ranges for synthetic data
parameter_ranges:
  voltage: [-3.6, 3.6]  # V
  thickness: [5e-9, 10e-9]  # m
  pulsewidth: [1e-7, 1e-6]  # s
  temperature: [250, 350]  # K
  
# Initial state generation
initial_state:
  method: "physics_based"  # or "random"
  base_defects: 10
  growth_factor: 0.1
  
# Output settings
output:
  format: "hdf5"  # or "csv"
  compression: "gzip"
  save_trajectories: true
  save_metadata: true