# config/physics_config.yaml

# Physical constants
constants:
  k_B: 8.617e-5  # Boltzmann constant in eV/K
  q: 1.602e-19  # Elementary charge in C
  epsilon_0: 8.854e-12  # Vacuum permittivity in F/m

# Trap parameters (based on the paper)
trap_parameters:
  chi_e: 2.4  # Electron affinity (eV)
  E_T_range: [2.0, 3.0]  # Thermal ionization energy (eV)
  delta_E_T_range: [0.5, 1.5]  # Thermal ionization spread (eV)
  phi_TE: 4.6  # Top electrode work function (eV)
  phi_BE: 4.6  # Bottom electrode work function (eV)
  E_REL_range: [1.0, 1.5]  # Relaxation energy (eV)
  N_T_range: [1e19, 5e19]  # Trap density (cm^-3)
  E_G: 5.8  # Bandgap (eV)

# Device parameters
device:
  thickness_default: 6e-9  # m
  area_default: 1e-12  # m^2
  temperature_default: 300  # K

# Kinetic Monte Carlo physics
kmc_physics:
  attempt_frequency: 1e13  # Hz
  field_acceleration_factor: 0.1  # Simplified
  generation_model: "thermochemical"  # or "trap_assisted"
  activation_energy: 1.0  # eV (based on paper ~1.0 eV)
  dipole_moment: 7e-29  # C*m (7 e*Angstrom from paper)

# Breakdown criteria
breakdown:
  defect_threshold: 200
  current_threshold: 1e-6  # A
  field_threshold: 10e6  # V/m


