# config/training_config.yaml

# Data configuration
data:
  csv_path: "data/kmc_run1_6nm_80dev_1.csv"
  initial_cycles: 5
  prediction_horizon: 50
  num_workers: 4
  train_split: 0.8
  
# Model configuration  
model:
  trap_dim: 8
  state_dim: 1
  latent_dim: 64
  hidden_dim: 128
  encoder_layers: 3
  evolution_layers: 2
  breakdown_threshold: 200.0
  
# Physics configuration
physics:
  temperature: 300.0  # K
  constants:
    k_B: 8.617e-5  # eV/K
    q: 1.602e-19   # C
  device:
    temperature_default: 300.0
    
# Training configuration
training:
  num_epochs: 100
  batch_size: 16
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  save_every: 10
  gradient_clip_val: 1.0
  use_wandb: false
  
# Optimizer configuration
optimizer:
  type: "adamw"
  lr: 0.0001  # Reduced from 0.001 for stability lr: 0.001
  weight_decay: 0.01
  
# Scheduler configuration
scheduler:
  type: "cosine"
  T_max: 100
  eta_min: 1.0e-6  # Fixed: Use proper float notation
  
# Loss configuration
loss:
  physics_informed:
    prediction_weight: 1.0
    breakdown_weight: 0.5
    monotonic_weight: 0.2
    smoothness_weight: 0.1
    physics_weight: 0.3
    breakdown_threshold: 200.0
  generation_weight: 0.3
  cycle_weight: 0.5