# config/training_config.yaml

# Model configuration
model:
  trap_dim: 8
  state_dim: 1
  latent_dim: 64
  hidden_dim: 128
  encoder_layers: 3
  evolution_layers: 2
  breakdown_threshold: 200.0
  use_fno: false  # Set to true to use Fourier Neural Operator

# Data configuration
data:
  csv_path: "data/kmc_run1_6nm_80dev 1.csv"
  initial_cycles: 5
  prediction_horizon: 50
  max_cycles: 2000
  breakdown_threshold: 200
  num_workers: 4
  normalize: true
  train_split: 0.75

# Training configuration
training:
  batch_size: 8  # Small batch size due to limited data
  num_epochs: 1000
  gradient_clip_val: 1.0
  save_every: 50
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  use_wandb: true
  resume_from: null  # Path to checkpoint to resume from

# Optimizer configuration
optimizer:
  type: "adamw"
  lr: 5.0e-4  # lower for stability
  weight_decay: 0.01

# Scheduler configuration
scheduler:
  type: "cosine"
  T_max: 500
  eta_min: 1.0e-6

# Loss configuration
loss:
  physics_informed:
    prediction_weight: 1.0
    breakdown_weight: 1.0 # 0.5
    monotonic_weight: 0.5  # 0.2
    smoothness_weight: 0.1
    physics_weight: 0.3
    breakdown_threshold: 200.0
  generation_weight: 0.2
  cycle_weight: 0.3

# Physics configuration
physics:
  temperature: 300.0  # Kelvin
  activation_energy_range: [1.0, 1.5]  # eV
  dipole_moment: 1.0e-29  # C*m

# Wandb configuration
wandb:
  project: "ferroelectric-sdg"
  run_name: "fe_surrogate_baseline"

# Device configuration
device: "cuda"


