# config/training_config.yaml

# Model configuration
model:
  trap_dim: 8
  state_dim: 1
  latent_dim: 64
  hidden_dim: 128
  encoder_layers: 3
  evolution_layers: 2
  breakdown_threshold: 200.0
  use_fno: false  # Set to true to use Fourier Neural Operator

# Data configuration
data:
  csv_path: "data/raw/kmc_run1_6nm_80dev_1.csv"
  initial_cycles: 5
  prediction_horizon: 50
  max_cycles: 2000
  breakdown_threshold: 200
  num_workers: 4
  normalize: true
  train_split: 0.75

# Training configuration
training:
  batch_size: 8  # Small batch size due to limited data
  num_epochs: 1000
  gradient_clip_val: 1.0
  save_every: 50
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  use_wandb: true
  resume_from: null  # Path to checkpoint to resume from

# Optimizer configuration
optimizer:
  type: "adamw"
  lr: 5.0e-4  # lower for stability
  weight_decay: 0.01

# Scheduler configuration
scheduler:
  type: "cosine"
  T_max: 500
  eta_min: 1.0e-6

# Loss configuration
loss:
  physics_informed:
    prediction_weight: 1.0
    breakdown_weight: 1.0 # 0.5
    monotonic_weight: 0.5  # 0.2
    smoothness_weight: 0.1
    physics_weight: 0.3
    breakdown_threshold: 200.0
  generation_weight: 0.2
  cycle_weight: 0.3

# Physics configuration
physics:
  temperature: 300.0  # Kelvin
  activation_energy_range: [1.0, 1.5]  # eV
  dipole_moment: 1.0e-29  # C*m

# Wandb configuration
wandb:
  project: "ferroelectric-sdg"
  run_name: "fe_surrogate_baseline"

# Device configuration
device: "cuda"

---
# config/physics_config.yaml

# Physical constants
constants:
  k_B: 8.617e-5  # Boltzmann constant in eV/K
  q: 1.602e-19  # Elementary charge in C
  epsilon_0: 8.854e-12  # Vacuum permittivity in F/m
  
# Trap parameters (based on the paper)
trap_parameters:
  chi_e: 2.4  # Electron affinity (eV)
  E_T_range: [2.0, 3.0]  # Thermal ionization energy (eV)
  delta_E_T_range: [0.5, 1.5]  # Thermal ionization spread (eV)
  phi_TE: 4.6  # Top electrode work function (eV)
  phi_BE: 4.6  # Bottom electrode work function (eV)
  E_REL_range: [1.0, 1.5]  # Relaxation energy (eV)
  N_T_range: [1e19, 5e19]  # Trap density (cm^-3)
  E_G: 5.8  # Bandgap (eV)

# Device parameters
device:
  thickness_default: 6e-9  # m
  area_default: 1e-12  # m^2
  temperature_default: 300  # K

# Kinetic Monte Carlo physics
kmc_physics:
  attempt_frequency: 1e13  # Hz
  field_acceleration_factor: 0.1  # Simplified
  generation_model: "thermochemical"  # or "trap_assisted"
  
# Breakdown criteria
breakdown:
  defect_threshold: 200
  current_threshold: 1e-6  # A
  field_threshold: 10e6  # V/m

---
# config/generation_config.yaml

# Generation settings
generation:
  num_samples: 1000
  max_cycles: 2000
  breakdown_threshold: 0.95  # Probability threshold
  
# Parameter ranges for synthetic data
parameter_ranges:
  voltage: [-3.6, 3.6]  # V
  thickness: [5e-9, 10e-9]  # m
  pulsewidth: [1e-7, 1e-6]  # s
  temperature: [250, 350]  # K
  
# Initial state generation
initial_state:
  method: "physics_based"  # or "random"
  base_defects: 10
  growth_factor: 0.1
  
# Output settings
output:
  format: "hdf5"  # or "csv"
  compression: "gzip"
  save_trajectories: true
  save_metadata: true