# config/training_config.yaml

# Data configuration
data:
  csv_path: "data/kmc_run1_6nm_80dev_1.csv"
  initial_cycles: 5
  prediction_horizon: 50
  num_workers: 4
  train_split: 0.8
  normalize: true
  seed: 42

# Model configuration
model:
  trap_dim: 8
  state_dim: 1
  latent_dim: 64
  hidden_dim: 128
  encoder_layers: 3
  evolution_layers: 2
  breakdown_threshold: 200.0
  use_fno: false

# Physics configuration
physics:
  temperature: 300.0  # Temperature in Kelvin
  constants:
    k_B: 8.617e-5  # Boltzmann constant in eV/K
    q: 1.602e-19   # Elementary charge in C
  device:
    temperature_default: 300.0  # Default device temperature in K

# Training configuration
training:
  batch_size: 32
  num_epochs: 100
  save_every: 10
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
  gradient_clip_val: 1.0
  use_wandb: false
  resume_from: null

# Optimizer configuration
optimizer:
  type: "adamw"
  lr: 1e-3
  weight_decay: 1e-4

# Scheduler configuration
scheduler:
  type: "cosine"
  T_max: 100
  eta_min: 1e-6

# Loss configuration
loss:
  physics_informed:
    prediction_weight: 1.0
    breakdown_weight: 0.5
    monotonic_weight: 0.2
    smoothness_weight: 0.1
    physics_weight: 0.3
  generation_weight: 0.1
  cycle_weight: 0.2